# Generated by Django 6.1 on 2026-08-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('DECORATION_RENTAL', "Location & Décoration d'événements"), ('GENERAL_INVENTORY', 'Gestion de Stock Général')], default='DECORATION_RENTAL', max_length=50),
        ),
    ]
