# Generated by Django 6.1 on 2026-08-17 08:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_reseed_roles_stock_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='entretien_requis',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='entretien_requis',
            field=models.BooleanField(blank=True, help_text='None = hérite de la catégorie (RM-08).', null=True),
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procedure_nom', models.CharField(max_length=200)),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('PARTIELLE', 'Partielle'), ('TERMINEE', 'Terminée')], default='EN_COURS', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_tasks', to='accounts.item')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='accounts.procedure')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.procedure'),
        ),
        migrations.AddField(
            model_name='item',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.procedure'),
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('obligatoire', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('OPERATION', 'Opération'), ('CONTROLE', 'Contrôle')], default='OPERATION', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='accounts.procedure')),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('obligatoire', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('OPERATION', 'Opération'), ('CONTROLE', 'Contrôle')], max_length=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='accounts.maintenancetask')),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='procedure',
            constraint=models.UniqueConstraint(fields=('business', 'nom'), name='unique_procedure_per_business'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['business', 'item', 'created_at'], name='idx_task_biz_item_date'),
        ),
        migrations.AddConstraint(
            model_name='procedurestep',
            constraint=models.UniqueConstraint(fields=('procedure', 'nom'), name='unique_procedure_step_name'),
        ),
    ]
