# Generated by Django 6.1 on 2026-08-17 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_reseed_roles_inventaire_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('ARTICLE_EN_ENTRETIEN', 'Sortir un article en entretien'), ('ENTRETIEN_PARTIEL', "Sortir un article à l'entretien partiel"), ('ARTICLE_A_VERIFIER', 'Sortir un article à vérifier')], max_length=40)),
                ('mode', models.CharField(choices=[('AVERTISSEMENT', 'Avertissement'), ('BLOCAGE', 'Blocage')], default='AVERTISSEMENT', max_length=15)),
                ('est_actif', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='accounts.business')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40)),
                ('mode', models.CharField(choices=[('AVERTISSEMENT', 'Avertissement'), ('BLOCAGE', 'Blocage')], max_length=15)),
                ('message', models.TextField()),
                ('quantite', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.business')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='accounts.item')),
                ('mouvement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='accounts.stockmovement')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='accounts.businessrule')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40)),
                ('motif', models.TextField()),
                ('quantite', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='accounts.business')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='accounts.item')),
                ('mouvement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='accounts.stockmovement')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='accounts.businessrule')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='businessrule',
            constraint=models.UniqueConstraint(fields=('business', 'code'), name='unique_rule_per_business'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['business', 'item', 'created_at'], name='idx_alert_biz_item_date'),
        ),
        migrations.AddIndex(
            model_name='decisionlog',
            index=models.Index(fields=['business', 'item', 'created_at'], name='idx_dec_biz_item_date'),
        ),
    ]
