# Generated by Django 6.1 on 2026-08-17 20:52

import django.db.models.deletion
import uuid
from django import VERSION as DJANGO_VERSION
from django.conf import settings
from django.db import migrations, models


def _check_constraint(condition, name):
    """CheckConstraint compatible Django >= 4.2 et >= 5.1 (`check=` vs `condition=`)."""
    if DJANGO_VERSION >= (5, 1):
        return models.CheckConstraint(condition=condition, name=name)
    return models.CheckConstraint(check=condition, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_reseed_roles_activity_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accounts.business')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='accounts.item')),
                ('reserve_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['business', 'created_at'], name='idx_res_biz_date'), models.Index(fields=['business', 'item', 'date_debut'], name='idx_res_biz_item_debut')],
                'constraints': [_check_constraint(models.Q(('date_fin__gte', models.F('date_debut'))), 'reservation_dates_coherentes')],
            },
        ),
    ]
