# Generated by Django 6.1 on 2026-08-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_reservation_controle_retour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='quantite_abimee',
            field=models.PositiveIntegerField(blank=True, help_text='Unités rendues abîmées (contrôle de retour).', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='quantite_perdue',
            field=models.PositiveIntegerField(blank=True, help_text='Unités perdues pendant la location.', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='quantite_retournee',
            field=models.PositiveIntegerField(blank=True, help_text='Unités rendues en bon état (contrôle de retour).', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='retourne_le',
            field=models.DateTimeField(blank=True, help_text='Moment du retour effectif.', null=True),
        ),
    ]
