# Generated by Django 6.1 on 2026-08-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_reservation_quantite_abimee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmember',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='code_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessmember',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INVITE', 'Invite'), ('BLOQUE', 'Bloque'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='INVITE', max_length=10),
        ),
    ]
