# Generated by Django 4.2.30 on 2026-08-20 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_businessmember_accepted_at_businessmember_code_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmember',
            name='device_type',
            field=models.CharField(blank=True, choices=[('IOS', 'iOS'), ('ANDROID', 'Android')], help_text="Type d'appareil pour les notifications push", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Token Firebase Cloud Messaging pour les notifications push', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='qr_code',
            field=models.CharField(blank=True, help_text='Code QR unique pour identification rapide (auto-généré si vide)', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text="Date d'assignation de la tâche", null=True),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Membre qui a assigné la tâche', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Membre assigné à cette tâche', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='cout_main_oeuvre',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Coût de la main d'oeuvre", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='cout_materiel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coût du matériel utilisé', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='cout_estime',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coût estimé pour cette procédure', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='taskstep',
            name='duree_estimee',
            field=models.DurationField(blank=True, help_text='Durée estimée pour cette étape', null=True),
        ),
        migrations.CreateModel(
            name='TaskStepPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='task_photos/%Y/%m/')),
                ('type', models.CharField(choices=[('AVANT', 'Avant'), ('APRES', 'Après')], max_length=5)),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='accounts.taskstep')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.maintenancetask')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rappel_a', models.DateTimeField(help_text='Date et heure du rappel')),
                ('message', models.CharField(max_length=255)),
                ('envoye', models.BooleanField(default=False, help_text='Le rappel a-t-il été envoyé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, help_text='Article associé (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='accounts.item')),
                ('task', models.ForeignKey(blank=True, help_text='Tâche associée (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='accounts.maintenancetask')),
                ('user', models.ForeignKey(help_text='Destinataire du rappel', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rappel_a'],
                'indexes': [models.Index(fields=['business', 'rappel_a', 'envoye'], name='idx_reminder_biz_time')],
            },
        ),
        migrations.CreateModel(
            name='RecurringTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequence_jours', models.PositiveIntegerField(default=7, help_text='Fréquence en jours (7 = hebdomadaire, 30 = mensuel)')),
                ('prochaine_execution', models.DateField(help_text='Date de la prochaine exécution prévue')),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_tasks', to='accounts.business')),
                ('category', models.ForeignKey(blank=True, help_text='Catégorie (si item est null)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_tasks', to='accounts.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, help_text='Article spécifique (null = tous les articles de la catégorie)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_tasks', to='accounts.item')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_tasks', to='accounts.procedure')),
            ],
            options={
                'ordering': ['prochaine_execution'],
                'indexes': [models.Index(fields=['business', 'prochaine_execution'], name='idx_recurring_biz_next')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FREQUENT_MAINTENANCE', 'Entretien trop fréquent'), ('LONG_DURATION', 'Durée anormale'), ('LOW_COMPLETION', 'Taux de complétion faible')], max_length=25)),
                ('seuil', models.JSONField(default=dict, help_text="Configuration du seuil qui a déclenché l'alerte")),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_alerts', to='accounts.business')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_alerts', to='accounts.item')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'resolved', 'created_at'], name='idx_perf_alert_biz_resolved')],
            },
        ),
    ]
