# Generated by Django 6.1 on 2026-08-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_idempotencyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='public_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='public_description',
            field=models.TextField(blank=True),
        ),
    ]
