# Generated by Django 6.1 on 2026-08-26 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_business_public_name_business_slug_item_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='contact_nom',
            field=models.CharField(blank=True, help_text='Personne contact sur place', max_length=150),
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_telephone',
            field=models.CharField(blank=True, help_text='Téléphone contact sur place', max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='lieu_adresse',
            field=models.TextField(blank=True, help_text='Adresse complète de livraison/reprise'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='lieu_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude GPS', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='lieu_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude GPS', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='lieu_nom',
            field=models.CharField(blank=True, help_text='Nom du lieu (ex: Salle des fêtes, Hôtel XYZ)', max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='livraison_effectuee_le',
            field=models.DateTimeField(blank=True, help_text='Date/heure réelle de livraison', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='livraison_prevue_le',
            field=models.DateTimeField(blank=True, help_text='Date/heure prévue de livraison', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='livreur',
            field=models.ForeignKey(blank=True, help_text='Membre qui a effectué la livraison', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_effectuees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes_livraison',
            field=models.TextField(blank=True, help_text='Instructions : étage, code porte, accès, etc.'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reprise_effectuee_le',
            field=models.DateTimeField(blank=True, help_text='Date/heure réelle de reprise', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reprise_par',
            field=models.ForeignKey(blank=True, help_text='Membre qui a effectué la reprise', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprises_effectuees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reprise_prevue_le',
            field=models.DateTimeField(blank=True, help_text='Date/heure prévue de reprise', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='statut_livraison',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de livraison'), ('LIVREE', 'Livrée'), ('REPRISE', 'Reprise (retour client)'), ('RETOURNEE', 'Retournée au dépôt')], default='EN_ATTENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='retourne_le',
            field=models.DateTimeField(blank=True, help_text='Moment du retour effectif au dépôt.', null=True),
        ),
    ]
