# Generated by Django 6.1 on 2026-08-26 12:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_reservation_contact_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_nom', models.CharField(max_length=150)),
                ('client_telephone', models.CharField(max_length=30)),
                ('client_email', models.EmailField(max_length=254)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True, help_text='Message du client (besoin, occasion, etc.)')),
                ('lieu_nom', models.CharField(blank=True, max_length=200)),
                ('lieu_adresse', models.TextField(blank=True)),
                ('contact_nom', models.CharField(blank=True, max_length=150)),
                ('contact_telephone', models.CharField(blank=True, max_length=30)),
                ('notes_livraison', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de traitement'), ('ACCEPTEE', "Acceptée par l'équipe"), ('REFUSEE', 'Refusée'), ('EXPIREE', 'Expirée (pas de réponse)'), ('ANNULEE_CLIENT', 'Annulée par le client'), ('CONVERTIE', 'Transformée en réservation')], default='EN_ATTENTE', max_length=20)),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True)),
                ('contre_proposition', models.JSONField(blank=True, help_text='Contre-proposition : {date_debut, date_fin, quantite, prix, message}', null=True)),
                ('access_token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text="Expiration du token d'accès (7 jours)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='accounts.business')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='accounts.item')),
                ('reservation_creee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_request_origine', to='accounts.reservation')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['business', 'statut', 'created_at'], name='idx_br_biz_statut_date'), models.Index(fields=['business', 'item', 'created_at'], name='idx_br_biz_item_date'), models.Index(fields=['access_token'], name='idx_br_token')],
            },
        ),
    ]
