# Generated by Django 6.1 on 2026-08-26 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_bookingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('type', models.CharField(choices=[('PROFORMA', 'Proforma (à la validation réservation)'), ('DEFINITIVE', 'Définitive (à la fin réservation)'), ('AVOIR', 'Avoir (remboursement/annulation)')], default='PROFORMA', max_length=15)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PROFORMA', 'Proforma'), ('DEFINITIVE', 'Définitive'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=15)),
                ('client_nom', models.CharField(max_length=150)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_telephone', models.CharField(blank=True, max_length=30)),
                ('client_adresse', models.TextField(blank=True)),
                ('lignes', models.JSONField(default=list, help_text='[{description, quantite, prix_unitaire, total}]')),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tva_taux', models.DecimalField(decimal_places=2, default=0, help_text='Ex: 18.00 pour 18%', max_digits=4)),
                ('tva_montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/')),
                ('generee_le', models.DateTimeField(auto_now_add=True)),
                ('envoyee_le', models.DateTimeField(blank=True, null=True)),
                ('payee_le', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.business')),
                ('generee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='accounts.reservation')),
            ],
            options={
                'ordering': ['-generee_le'],
                'indexes': [models.Index(fields=['business', 'numero'], name='idx_inv_biz_num'), models.Index(fields=['business', 'statut'], name='idx_inv_biz_statut')],
            },
        ),
    ]
