# Generated by Django 6.1 on 2026-08-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text="Clé d'idempotence pour éviter les doublons", max_length=100),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='visitor_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identifiant anonyme du navigateur', max_length=64),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='statut',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('EN_ATTENTE', 'En attente de traitement'), ('ACCEPTEE', "Acceptée par l'équipe"), ('REFUSEE', 'Refusée'), ('EXPIREE', 'Expirée (pas de réponse)'), ('ANNULEE_CLIENT', 'Annulée par le client'), ('CONVERTIE', 'Transformée en réservation')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['visitor_id'], name='idx_br_visitor'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['idempotency_key'], name='idx_br_idem'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['business', 'visitor_id', 'statut'], name='idx_br_biz_vis_statut'),
        ),
    ]
