# Generated by Django 6.1 on 2026-08-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_bookingrequest_visitor_idempotency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='numero',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('business', 'numero'), name='uniq_invoice_business_numero'),
        ),
    ]
